Open the server in both database configurations

diff --git a/.github/workflows/build_pull_request.yml b/.github/workflows/build_pull_request.yml
--- a/.github/workflows/build_pull_request.yml
+++ b/.github/workflows/build_pull_request.yml
@@ -66,8 +66,27 @@ jobs:
           gcc -fPIC -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -shared scripts/resources/catch_abort.c -lpthread -o scripts/resources/catch_abort.so
           export LD_PRELOAD="$(pwd)/scripts/resources/catch_abort.so"
           JAR=$(ls ./server/build/*.jar| head -1)
-          timeout 1m java -Dsuwayomi.tachidesk.config.server.databaseType=POSTGRESQL \
+          timeout 30s java -Dsuwayomi.tachidesk.config.server.initialOpenInBrowserEnabled=false \
+              -Dsuwayomi.tachidesk.config.server.databaseType=POSTGRESQL \
               -Dsuwayomi.tachidesk.config.server.databaseUrl=postgresql://localhost:5432/postgres \
               -Dsuwayomi.tachidesk.config.server.databaseUsername=postgres \
               -Dsuwayomi.tachidesk.config.server.databasePassword=postgres \
               -jar "$JAR"
+
+          ecode="$?"
+          # if exit code is not 124 or 125, then error
+          if ! [ "$ecode" -eq 124 -o "$ecode" -eq 125 ]; then 
+            printf "exit code '%s' - exiting.\n" "$ecode"
+            exit "$ecode"
+          fi
+
+          timeout 30s java -Dsuwayomi.tachidesk.config.server.initialOpenInBrowserEnabled=false \
+              -jar "$JAR"
+
+          ecode="$?"
+          # if exit code is not 124 or 125, then error
+          if ! [ "$ecode" -eq 124 -o "$ecode" -eq 125 ]; then 
+            printf "exit code '%s' - exiting.\n" "$ecode"
+            exit "$ecode"
+          fi
+          exit 0
